In [1]:
import pandas as pd
import os

In [3]:
dataset1 = pd.read_excel("Final_outputs.xlsx")
dataset1

,Unnamed: 0,ResponseID,StudentID\n(ePunjabID),Language,Country,City,State/Region,Postal,dob_year,dob_month,...,hh_size,mother_education,father_education,Stream,personal_phone,Gender,Question,Answer,Respondents,same_answer
0,0,462,5217774,Hindi,India,Ludhiana,23.0,141015.0,2007.0,January,...,4,12thpass,12thpass,Science,Yes,Male,1a_grit_localtravel,"(a)yes,manytimes",4064,1908
1,1,463,12215275,Hindi,India,Ludhiana,23.0,141007.0,2004.0,July,...,6,Noeducation,9thstandardorless,Science,Yes,Male,1a_grit_localtravel,"(b)yes,sometimes",4064,877
2,2,464,4680164,Hindi,India,Ludhiana,23.0,141007.0,2005.0,March,...,7,10thpassormatriculation,Post-Graduation,Science,No,Male,1a_grit_localtravel,"(b)yes,sometimes",4064,877
3,3,465,5510956,Hindi,India,NaN,NaN,NaN,2006.0,May,...,5,Post-graduation,Post-Graduation,Science,Yes,Female,1a_grit_localtravel,"(b)yes,sometimes",4064,877
4,4,466,11761609,Hindi,India,Ludhiana,23.0,141015.0,2004.0,Februrary,...,4,10thpassormatriculation,10thpassormatriculation,Arts,Yes,Male,1a_grit_localtravel,"(b)yes,sometimes",4064,877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166619,166619,9274,3312529,Hindi,India,Ludhiana,23.0,141203.0,2007.0,August,...,11,10thpassormatriculation,10thpassormatriculation,Arts,Yes,Male,20b_ind_informeddecision,NaN,248,0
166620,166620,9284,13620228,Hindi,India,Ludhiana,23.0,142022.0,2005.0,September,...,4,Noeducation,Noeducation,Arts,No,Male,20b_ind_informeddecision,NaN,248,0
166621,166621,9292,9249664,Hindi,India,Mohali,23.0,140308.0,2006.0,June,...,6,Noeducation,Noeducation,Arts,Yes,Male,20b_ind_informeddecision,NaN,248,0
166622,166622,9293,3284667,Hindi,India,NaN,NaN,NaN,2007.0,March,...,6,10thpassormatriculation,9thstandardorless,Vocational,Yes,Male,20b_ind_informeddecision,NaN,248,0
166623,166623,9295,5544026,Hindi,India,Ludhiana,23.0,141002.0,2004.0,December,...,4,9thstandardorless,12thpass,Arts,Yes,Female,20b_ind_informeddecision,NaN,248,0

In [20]:
dataset1

,Unnamed: 0,ResponseID,StudentID\n(ePunjabID),Language,Country,City,State/Region,Postal,dob_year,dob_month,...,hh_size,mother_education,father_education,Stream,personal_phone,Gender,Question,Answer,Respondents,same_answer
0,0,462,5217774,Hindi,India,Ludhiana,23.0,141015.0,2007.0,January,...,4,12thpass,12thpass,Science,Yes,Male,1a_grit_localtravel,"(a)yes,manytimes",4064,1908
1,1,463,12215275,Hindi,India,Ludhiana,23.0,141007.0,2004.0,July,...,6,Noeducation,9thstandardorless,Science,Yes,Male,1a_grit_localtravel,"(b)yes,sometimes",4064,877
2,2,464,4680164,Hindi,India,Ludhiana,23.0,141007.0,2005.0,March,...,7,10thpassormatriculation,Post-Graduation,Science,No,Male,1a_grit_localtravel,"(b)yes,sometimes",4064,877
3,3,465,5510956,Hindi,India,NaN,NaN,NaN,2006.0,May,...,5,Post-graduation,Post-Graduation,Science,Yes,Female,1a_grit_localtravel,"(b)yes,sometimes",4064,877
4,4,466,11761609,Hindi,India,Ludhiana,23.0,141015.0,2004.0,Februrary,...,4,10thpassormatriculation,10thpassormatriculation,Arts,Yes,Male,1a_grit_localtravel,"(b)yes,sometimes",4064,877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166619,166619,9274,3312529,Hindi,India,Ludhiana,23.0,141203.0,2007.0,August,...,11,10thpassormatriculation,10thpassormatriculation,Arts,Yes,Male,20b_ind_informeddecision,NaN,248,0
166620,166620,9284,13620228,Hindi,India,Ludhiana,23.0,142022.0,2005.0,September,...,4,Noeducation,Noeducation,Arts,No,Male,20b_ind_informeddecision,NaN,248,0
166621,166621,9292,9249664,Hindi,India,Mohali,23.0,140308.0,2006.0,June,...,6,Noeducation,Noeducation,Arts,Yes,Male,20b_ind_informeddecision,NaN,248,0
166622,166622,9293,3284667,Hindi,India,NaN,NaN,NaN,2007.0,March,...,6,10thpassormatriculation,9thstandardorless,Vocational,Yes,Male,20b_ind_informeddecision,NaN,248,0
166623,166623,9295,5544026,Hindi,India,Ludhiana,23.0,141002.0,2004.0,December,...,4,9thstandardorless,12thpass,Arts,Yes,Female,20b_ind_informeddecision,NaN,248,0

In [5]:
car = dataset1.groupby('Question')['Answer'].value_counts()

In [18]:
index_names = dataset1[dataset1['Question'] =="10a_tnt_project_example"].index
index_names

Int64Index([77216, 77217, 77218, 77219, 77220, 77221, 77222, 77223, 77224,
            77225,
            ...
            81270, 81271, 81272, 81273, 81274, 81275, 81276, 81277, 81278,
            81279],
           dtype='int64', length=4064)

In [19]:
dataset1.drop(index_names, inplace = True)

In [22]:
output = dataset1.groupby('Question')['Answer'].value_counts()

In [23]:
output

Question           Answer
10a_tnt_project    (b)no                                           3121
                   (a)yes                                           943
10b_tnt_project    (c)Wantedto,butdidnothavetheopportunity         1504
                   (a)Didnotneedto                                  895
                   (b)Didnotwantto                                  432
                                                                   ...
9a_tnt_risktaking  (d)no                                            720
9b_tnt_risktaking  (a)Didnotneedto                                  366
                   (b)Didnotwantto                                  185
                   (c)Wantedto,butdidnothavetheopportunity           95
                   (d)Wasnotallowed(byfamily/caregiver/teacher)      73
Name: Answer, Length: 158, dtype: int64

In [24]:
output.to_csv("qna_based.csv")

In [10]:
dataset1.Question

0              1a_grit_localtravel
1              1a_grit_localtravel
2              1a_grit_localtravel
3              1a_grit_localtravel
4              1a_grit_localtravel
                    ...
166619    20b_ind_informeddecision
166620    20b_ind_informeddecision
166621    20b_ind_informeddecision
166622    20b_ind_informeddecision
166623    20b_ind_informeddecision
Name: Question, Length: 166624, dtype: object

In [3]:
df = pd.read_excel("March_baseline_final - Copy.xlsx",  sheet_name=0)
df

,ResponseID,StudentID\n(ePunjabID),Language,Country,City,State/Region,Postal,dob_year,dob_month,dob_date,...,16a_ind_doingthingsalone,16b_sa_doingthingsalone,17a_ind_againstnorm,17b_ind_againstnorm,18a_ind_reflection,18b_ind_reflection,19a_ind_questioning,19b_ind_questioning,20a_ind_informeddecision,20b_ind_informeddecision
0,462,5217774,Hindi,India,Ludhiana,23.0,141015.0,2007.0,January,23.0,...,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN
1,463,12215275,Hindi,India,Ludhiana,23.0,141007.0,2004.0,July,1.0,...,"(b)yes,sometimes",NaN,"(c)yes,onceortwice",NaN,"(b)yes,sometimes",NaN,(d)no,(b)Didnotwantto,"(b)yes,sometimes",NaN
2,464,4680164,Hindi,India,Ludhiana,23.0,141007.0,2005.0,March,7.0,...,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN,"(b)yes,sometimes",NaN,"(b)yes,sometimes",NaN,"(a)yes,manytimes",NaN
3,465,5510956,Hindi,India,NaN,NaN,NaN,2006.0,May,16.0,...,"(a)yes,manytimes",NaN,"(b)yes,sometimes",NaN,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN
4,466,11761609,Hindi,India,Ludhiana,23.0,141015.0,2004.0,Februrary,3.0,...,"(a)yes,manytimes",NaN,(d)no,(a)Didnotneedto,(d)no,(a)Didnotneedto,(d)no,"(c)Wantedto,butdidnothavetheopportunity","(a)yes,manytimes",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4059,9274,3312529,Hindi,India,Ludhiana,23.0,141203.0,2007.0,August,29.0,...,"(a)yes,manytimes",NaN,"(b)yes,sometimes",NaN,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN
4060,9284,13620228,Hindi,India,Ludhiana,23.0,142022.0,2005.0,September,6.0,...,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN,"(b)yes,sometimes",NaN,"(c)yes,onceortwice",NaN
4061,9292,9249664,Hindi,India,Mohali,23.0,140308.0,2006.0,June,9.0,...,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN,"(a)yes,manytimes",NaN,(d)no,(a)Didnotneedto,"(a)yes,manytimes",NaN
4062,9293,3284667,Hindi,India,NaN,NaN,NaN,2007.0,March,26.0,...,"(b)yes,sometimes",NaN,"(b)yes,sometimes",NaN,"(a)yes,manytimes",NaN,"(b)yes,sometimes",NaN,"(a)yes,manytimes",NaN
4063,9295,5544026,Hindi,India,Ludhiana,23.0,141002.0,2004.0,December,24.0,...,"(b)yes,sometimes",NaN,(d)no,(b)Didnotwantto,(d)no,(a)Didnotneedto,"(a)yes,manytimes",NaN,"(b)yes,sometimes",NaN

In [4]:
percent= 100*(len(df.loc[:,df.isnull().sum(axis=0)>=1 ].index) / len(df.index))
print(round(percent,2))

100.0

In [6]:
percent_missing = df.isnull().sum() * 100 / len(df)
missing_value_df = pd.DataFrame({'column_name': df.columns,
                                 'percent_missing': percent_missing})

In [7]:
missing_value_df.sort_values('percent_missing', inplace=True)

In [8]:
percent_missing

ResponseID                   0.000000
StudentID\n(ePunjabID)       0.000000
Language                     0.000000
Country                      0.172244
City                         8.661417
State/Region                 8.193898
Postal                       8.735236
dob_year                     0.049213
dob_month                    0.049213
dob_date                     0.049213
Class                        0.000000
Section                      0.000000
hh_size                      0.000000
mother_education             0.000000
father_education             0.000000
Stream                       0.000000
personal_phone               0.000000
Gender                       0.000000
1a_grit_localtravel          0.000000
1b_grit_localtravel         78.764764
2a_grit_errands              0.000000
2b_grit_errands             93.651575
3a_grit_publicspeaking       0.000000
3b_grit_publicspeaking      64.050197
4a_grit_discussion           0.000000
4b_grit_discussion          68.700787
5a_grit_persevered           0.000000
5b_grit_persevered          89.370079
6a_tnt_extraleadership       0.000000
6b_tnt_extraleadership      80.511811
7a_tnt_newskill              0.000000
7b_tnt_newskill             89.714567
8a_tnt_helpingothers         0.000000
8b_tnt_helpingothers        93.996063
9a_tnt_risktaking            0.000000
9b_tnt_risktaking           82.308071
10a_tnt_project              0.000000
10a_tnt_project_example     76.845472
10b_tnt_project             23.203740
11a_sa_feedback              0.000000
11b_sa_feedback             84.424213
12a_sa_helpseeking           0.049213
12b_sa_helpseeking          91.240157
13a_sa_values                0.049213
13b_sa_values               89.911417
14a_sa_emotions              0.049213
14b_sa_emotions             86.884843
15a_sa_influence             0.049213
15b_sa_influence            83.144685
16a_ind_doingthingsalone     0.049213
16b_sa_doingthingsalone     92.372047
17a_ind_againstnorm          0.147638
17b_ind_againstnorm         77.928150
18a_ind_reflection           0.196850
18b_ind_reflection          72.810039
19a_ind_questioning          0.196850
19b_ind_questioning         81.496063
20a_ind_informeddecision     0.196850
20b_ind_informeddecision    93.897638
dtype: float64

In [9]:
missing_value_df

                                       column_name  percent_missing
ResponseID                              ResponseID         0.000000
11a_sa_feedback                    11a_sa_feedback         0.000000
10a_tnt_project                    10a_tnt_project         0.000000
9a_tnt_risktaking                9a_tnt_risktaking         0.000000
8a_tnt_helpingothers          8a_tnt_helpingothers         0.000000
7a_tnt_newskill                    7a_tnt_newskill         0.000000
6a_tnt_extraleadership      6a_tnt_extraleadership         0.000000
5a_grit_persevered              5a_grit_persevered         0.000000
4a_grit_discussion              4a_grit_discussion         0.000000
2a_grit_errands                    2a_grit_errands         0.000000
1a_grit_localtravel            1a_grit_localtravel         0.000000
Gender                                      Gender         0.000000
personal_phone                      personal_phone         0.000000
Stream                                      Stream         0.000000
3a_grit_publicspeaking      3a_grit_publicspeaking         0.000000
mother_education                  mother_education         0.000000
hh_size                                    hh_size         0.000000
Section                                    Section         0.000000
Class                                        Class         0.000000
StudentID\n(ePunjabID)      StudentID\n(ePunjabID)         0.000000
Language                                  Language         0.000000
father_education                  father_education         0.000000
15a_sa_influence                  15a_sa_influence         0.049213
12a_sa_helpseeking              12a_sa_helpseeking         0.049213
16a_ind_doingthingsalone  16a_ind_doingthingsalone         0.049213
dob_year                                  dob_year         0.049213
14a_sa_emotions                    14a_sa_emotions         0.049213
dob_date                                  dob_date         0.049213
dob_month                                dob_month         0.049213
13a_sa_values                        13a_sa_values         0.049213
17a_ind_againstnorm            17a_ind_againstnorm         0.147638
Country                                    Country         0.172244
19a_ind_questioning            19a_ind_questioning         0.196850
20a_ind_informeddecision  20a_ind_informeddecision         0.196850
18a_ind_reflection              18a_ind_reflection         0.196850
State/Region                          State/Region         8.193898
City                                          City         8.661417
Postal                                      Postal         8.735236
10b_tnt_project                    10b_tnt_project        23.203740
3b_grit_publicspeaking      3b_grit_publicspeaking        64.050197
4b_grit_discussion              4b_grit_discussion        68.700787
18b_ind_reflection              18b_ind_reflection        72.810039
10a_tnt_project_example    10a_tnt_project_example        76.845472
17b_ind_againstnorm            17b_ind_againstnorm        77.928150
1b_grit_localtravel            1b_grit_localtravel        78.764764
6b_tnt_extraleadership      6b_tnt_extraleadership        80.511811
19b_ind_questioning            19b_ind_questioning        81.496063
9b_tnt_risktaking                9b_tnt_risktaking        82.308071
15b_sa_influence                  15b_sa_influence        83.144685
11b_sa_feedback                    11b_sa_feedback        84.424213
14b_sa_emotions                    14b_sa_emotions        86.884843
5b_grit_persevered              5b_grit_persevered        89.370079
7b_tnt_newskill                    7b_tnt_newskill        89.714567
13b_sa_values                        13b_sa_values        89.911417
12b_sa_helpseeking              12b_sa_helpseeking        91.240157
16b_sa_doingthingsalone    16b_sa_doingthingsalone        92.372047
2b_grit_errands                    2b_grit_errands        93.651575
20b_ind_informeddecision  20b_ind_informeddecision        93.897638
8b_tnt_helpingothers          8b_tnt_helpingothers        93.996063

In [18]:
missing_value_df.to_excel("missing1.xlsx")

In [2]:
df = pd.read_excel("Rfile_ex.xlsx")
df

,Response_ID,Time_Started,Date_Submitted,Status,Contact_ID,Legacy_Comments,Comments,Language,Referer,SessionID,...,17a_ind_againstnorm,17b_ind_againstnorm,18a_ind_reflection,18b_ind_reflection,19a_ind_questioning,19b_ind_questioning,20a_ind_informeddecision,20b_ind_informeddecision,survey_duration,open_comment
0,462,2022-11-04 23:42:25,2022-11-04 23:49:06,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1667585527_636555f798ba98.87695211,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,306,NaN
1,463,2022-11-05 00:03:18,2022-11-05 00:16:09,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1667586791_63655ae706fa24.54407997,...,"(c) ਹਾਂ, ਇੱਕ ਜਾਂ ਦੋ ਵਾਰ / yes, once or twice",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,(d) ਨਹੀਂ / no,(b) ਮੈਂ ਨਹੀਂ ਚਾਹੁੰਦਾ ਸੀ / Did not want to,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,651,NaN
2,464,2022-11-05 00:16:57,2022-11-05 00:20:19,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1667587614_63655e1e29d755.16629947,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,77,NaN
3,465,2022-11-05 00:27:55,2022-11-05 00:32:36,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1667588253_6365609dc45dd3.45151255,...,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,188,Future doctor
4,466,2022-11-05 04:23:57,2022-11-05 04:33:33,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1667602420_636597f49b4826.06236492,...,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,(d) ਨਹੀਂ / no,"(c) ਮੈਂ ਕਰਨਾ ਚਾਹੁੰਦਾ/ਚਾਹੁੰਦੀ ਸੀ, ਪਰ ਮੌਕਾ ਨਹੀਂ ...","(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,493,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5353,9284,2022-11-28 04:27:36,2022-11-28 04:38:09,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1669589853_6383eb5d707ee7.62173523,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(c) ਹਾਂ, ਇੱਕ ਜਾਂ ਦੋ ਵਾਰ / yes, once or twice",NaN,484,Sarve number kuchh nahin kar sakta aur ghar wa...
5354,9292,2022-11-28 13:57:28,2022-11-28 14:01:56,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1669624038_638470e65adb26.00778922,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,212,NaN
5355,9293,2022-11-28 14:43:04,2022-11-28 14:45:36,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1669626776_63847b984bc069.01579430,...,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,69,NaN
5356,9294,2022-11-28 15:02:49,2022-11-28 15:12:42,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1669627952_63848030838a94.91203939,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,(d) ਨਹੀਂ / no,"(c) ਮੈਂ ਕਰਨਾ ਚਾਹੁੰਦਾ/ਚਾਹੁੰਦੀ ਸੀ, ਪਰ ਮੌਕਾ ਨਹੀਂ ...","(c) ਹਾਂ, ਇੱਕ ਜਾਂ ਦੋ ਵਾਰ / yes, once or twice",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,500,NaN
5357,9295,2022-11-28 18:40:27,2022-11-28 18:53:50,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1669641022_6384b33e983a23.32849690,...,(d) ਨਹੀਂ / no,(b) ਮੈਂ ਨਹੀਂ ਚਾਹੁੰਦਾ ਸੀ / Did not want to,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,702,NaN

In [4]:
df = df.drop_duplicates(subset='Student_ID', keep="first")
df

,Response_ID,Time_Started,Date_Submitted,Status,Contact_ID,Legacy_Comments,Comments,Language,Referer,SessionID,...,17a_ind_againstnorm,17b_ind_againstnorm,18a_ind_reflection,18b_ind_reflection,19a_ind_questioning,19b_ind_questioning,20a_ind_informeddecision,20b_ind_informeddecision,survey_duration,open_comment
0,462,2022-11-04 23:42:25,2022-11-04 23:49:06,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1667585527_636555f798ba98.87695211,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,306,NaN
1,463,2022-11-05 00:03:18,2022-11-05 00:16:09,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1667586791_63655ae706fa24.54407997,...,"(c) ਹਾਂ, ਇੱਕ ਜਾਂ ਦੋ ਵਾਰ / yes, once or twice",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,(d) ਨਹੀਂ / no,(b) ਮੈਂ ਨਹੀਂ ਚਾਹੁੰਦਾ ਸੀ / Did not want to,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,651,NaN
2,464,2022-11-05 00:16:57,2022-11-05 00:20:19,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1667587614_63655e1e29d755.16629947,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,77,NaN
3,465,2022-11-05 00:27:55,2022-11-05 00:32:36,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1667588253_6365609dc45dd3.45151255,...,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,188,Future doctor
4,466,2022-11-05 04:23:57,2022-11-05 04:33:33,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1667602420_636597f49b4826.06236492,...,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,(d) ਨਹੀਂ / no,"(c) ਮੈਂ ਕਰਨਾ ਚਾਹੁੰਦਾ/ਚਾਹੁੰਦੀ ਸੀ, ਪਰ ਮੌਕਾ ਨਹੀਂ ...","(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,493,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5352,9276,2022-11-27 19:16:16,2022-11-27 19:28:42,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1669556759_63836a17a4b618.07440769,...,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(c) ਹਾਂ, ਇੱਕ ਜਾਂ ਦੋ ਵਾਰ / yes, once or twice",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,574,NaN
5353,9284,2022-11-28 04:27:36,2022-11-28 04:38:09,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1669589853_6383eb5d707ee7.62173523,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(c) ਹਾਂ, ਇੱਕ ਜਾਂ ਦੋ ਵਾਰ / yes, once or twice",NaN,484,Sarve number kuchh nahin kar sakta aur ghar wa...
5354,9292,2022-11-28 13:57:28,2022-11-28 14:01:56,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1669624038_638470e65adb26.00778922,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,212,NaN
5355,9293,2022-11-28 14:43:04,2022-11-28 14:45:36,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1669626776_63847b984bc069.01579430,...,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,69,NaN
5357,9295,2022-11-28 18:40:27,2022-11-28 18:53:50,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,1669641022_6384b33e983a23.32849690,...,(d) ਨਹੀਂ / no,(b) ਮੈਂ ਨਹੀਂ ਚਾਹੁੰਦਾ ਸੀ / Did not want to,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,702,NaN

In [5]:
df.to_excel("duplicate_gon.xlsx")

In [6]:
df = pd.read_excel("duplicate_gon.xlsx")
df

,Unnamed: 0,Response_ID,Time_Started,Date_Submitted,Status,Contact_ID,Legacy_Comments,Comments,Language,Referer,...,17a_ind_againstnorm,17b_ind_againstnorm,18a_ind_reflection,18b_ind_reflection,19a_ind_questioning,19b_ind_questioning,20a_ind_informeddecision,20b_ind_informeddecision,survey_duration,open_comment
0,0,462,2022-11-04 23:42:25,2022-11-04 23:49:06,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,306,NaN
1,1,463,2022-11-05 00:03:18,2022-11-05 00:16:09,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,"(c) ਹਾਂ, ਇੱਕ ਜਾਂ ਦੋ ਵਾਰ / yes, once or twice",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,(d) ਨਹੀਂ / no,(b) ਮੈਂ ਨਹੀਂ ਚਾਹੁੰਦਾ ਸੀ / Did not want to,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,651,NaN
2,2,464,2022-11-05 00:16:57,2022-11-05 00:20:19,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,77,NaN
3,3,465,2022-11-05 00:27:55,2022-11-05 00:32:36,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,188,Future doctor
4,4,466,2022-11-05 04:23:57,2022-11-05 04:33:33,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,(d) ਨਹੀਂ / no,"(c) ਮੈਂ ਕਰਨਾ ਚਾਹੁੰਦਾ/ਚਾਹੁੰਦੀ ਸੀ, ਪਰ ਮੌਕਾ ਨਹੀਂ ...","(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,493,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4288,5352,9276,2022-11-27 19:16:16,2022-11-27 19:28:42,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(c) ਹਾਂ, ਇੱਕ ਜਾਂ ਦੋ ਵਾਰ / yes, once or twice",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,574,NaN
4289,5353,9284,2022-11-28 04:27:36,2022-11-28 04:38:09,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(c) ਹਾਂ, ਇੱਕ ਜਾਂ ਦੋ ਵਾਰ / yes, once or twice",NaN,484,Sarve number kuchh nahin kar sakta aur ghar wa...
4290,5354,9292,2022-11-28 13:57:28,2022-11-28 14:01:56,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,212,NaN
4291,5355,9293,2022-11-28 14:43:04,2022-11-28 14:45:36,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,69,NaN
4292,5357,9295,2022-11-28 18:40:27,2022-11-28 18:53:50,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,(d) ਨਹੀਂ / no,(b) ਮੈਂ ਨਹੀਂ ਚਾਹੁੰਦਾ ਸੀ / Did not want to,(d) ਨਹੀਂ / no,(a) ਲੋੜ ਨਹੀਂ ਸੀ / Did not need to,"(a) ਹਾਂ, ਕਈ ਵਾਰ / yes, many times",NaN,"(b) ਹਾਂ, ਕਦੀ ਕਦੀ / yes, sometimes",NaN,702,NaN

In [8]:
df1 = pd.read_excel("students_data.xlsx")
df1

,Student_ID,Student Name,Gender,Class,Section,Stream,UDISE Code,School Name,School Id
0,1992014,SIMRAN KAUR,Female,12,F,Vocational,3090508902,GMSSS P.A.U.,3090508902
1,2270370,SACHIN KUMAR,Male,12,N,Commerce,3090508902,GMSSS P.A.U.,3090508902
2,2351011,SIMRAN DEEP SINGH,Male,12,H,Vocational,3090508902,GMSSS P.A.U.,3090508902
3,2614447,PALVINDER SINGH,Male,11,C,Arts,3040111410,FREEDOM FIGHTER SH. AJIT SAINI GMSSS CO-ED LAD...,3040111410
4,2614551,SHIVAM,Male,11,E,Commerce,3040111410,FREEDOM FIGHTER SH. AJIT SAINI GMSSS CO-ED LAD...,3040111410
...,...,...,...,...,...,...,...,...,...
21493,13038034,KHUSHDEEP SINGH,Male,11,D,Science,3160907204,"RESIDENTIAL SCHOOL FOR MERITORIUS STUDENTS, SA...",3160907204
21494,13581085,DEEPINDER KAUR,Female,11,A,Science,3160907204,"RESIDENTIAL SCHOOL FOR MERITORIUS STUDENTS, SA...",3160907204
21495,13615613,BARINDERDEEP KAUR,Female,11,B,Science,3160907204,"RESIDENTIAL SCHOOL FOR MERITORIUS STUDENTS, SA...",3160907204
21496,13700533,EKTA,Female,11,B,Science,3160907204,"RESIDENTIAL SCHOOL FOR MERITORIUS STUDENTS, SA...",3160907204
21497,11111111,DUMMY STUDENT,Female,11,Z,Arts,1111111111,DUMMY SCHOOL,1111111111

In [13]:
df_merge = pd.merge(df, df1, on='Student_ID')

In [14]:
df_merge

,Unnamed: 0,Response_ID,Time_Started,Date_Submitted,Status,Contact_ID,Legacy_Comments,Comments,Language,Referer,...,survey_duration,open_comment,Student Name,Gender,Class,Section,Stream,UDISE Code,School Name,School Id
0,0,462,2022-11-04 23:42:25,2022-11-04 23:49:06,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,306,NaN,GOURAV KOUNDAL,Male,11,F,Science,3050900603,GSSS KAMAHI DEVI,3050900603
1,1,463,2022-11-05 00:03:18,2022-11-05 00:16:09,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,651,NaN,PAWAN KUMAR,Male,11,B,Science,3180212502,GSSS PHASE IIIB I,3180212502
2,2,464,2022-11-05 00:16:57,2022-11-05 00:20:19,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,77,NaN,SAKET SHARMA,Male,11,B,Science,3180212502,GSSS PHASE IIIB I,3180212502
3,3,465,2022-11-05 00:27:55,2022-11-05 00:32:36,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,188,Future doctor,KASHISH,Female,11,F,Science,3040111410,FREEDOM FIGHTER SH. AJIT SAINI GMSSS CO-ED LAD...,3040111410
4,4,466,2022-11-05 04:23:57,2022-11-05 04:33:33,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,493,NaN,JATINDERPAL SINGH,Male,11,B,Arts,3161305702,COMRADE BHIM SINGH GOVERNMENT SENIOR SECONDARY...,3161305702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4059,5350,9274,2022-11-27 18:45:27,2022-11-27 18:50:56,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,238,No,AKASHDEEP SINGH,Male,11,D,Arts,3090501503,GSSS DAKHA,3090501503
4060,5353,9284,2022-11-28 04:27:36,2022-11-28 04:38:09,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,484,Sarve number kuchh nahin kar sakta aur ghar wa...,GURJINDER SINGH,Male,11,F,Arts,3180108702,GSSS LALRU MANDI,3180108702
4061,5354,9292,2022-11-28 13:57:28,2022-11-28 14:01:56,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,212,NaN,VISHAL KUMAR,Male,11,D,Arts,3090501503,GSSS DAKHA,3090501503
4062,5355,9293,2022-11-28 14:43:04,2022-11-28 14:45:36,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,69,NaN,DEEPAK SINGH,Male,11,E,Vocational,3090501503,GSSS DAKHA,3090501503
4063,5357,9295,2022-11-28 18:40:27,2022-11-28 18:53:50,Complete,NaN,NaN,NaN,Hindi,https://survey.alchemer.com/s3/7079461/PunjabB...,...,702,NaN,VISHAKHA,Female,11,L,Arts,3040111316,AMAR SHAHEED LALA JAGAT NARAYAN GGSSS NEHRU GA...,3040111316

In [15]:
df_merge.to_excel("merged.xlsx")

In [18]:
df_merge.describe()

,Unnamed: 0,Response_ID,Contact_ID,Legacy_Comments,Comments,Tags,Longitude,Latitude,Postal,dob_year,dob_date,hh_size,Student_ID,demographic_duration,survey_duration,Class,UDISE Code,School Id
count,4064.000000,4064.000000,0.0,0.0,0.0,0.0,4057.000000,4057.000000,3709.000000,4062.000000,4062.000000,4064.000000,4.064000e+03,4064.00000,4.064000e+03,4064.000000,4.064000e+03,4.064000e+03
mean,2449.851870,4368.729085,NaN,NaN,NaN,NaN,76.485645,29.434644,173835.702076,2005.779419,15.263909,5.238189,6.194954e+06,1206.41314,4.746873e+03,11.001476,3.099727e+09,3.099727e+09
std,1512.729922,2471.685487,NaN,NaN,NaN,NaN,5.356819,3.689996,118174.773953,1.081323,8.833365,2.083504,2.728681e+06,23127.66900,7.202259e+04,0.038400,6.691298e+07,6.691298e+07
min,0.000000,462.000000,NaN,NaN,NaN,NaN,-97.821999,1.367300,75201.000000,2001.000000,1.000000,0.000000,1.656145e+06,23.00000,1.000000e+00,11.000000,1.111111e+09,1.111111e+09
25%,1118.500000,2178.750000,NaN,NaN,NaN,NaN,75.946297,30.733900,141007.000000,2005.000000,8.000000,4.000000,4.053709e+06,86.00000,2.960000e+02,11.000000,3.050306e+09,3.050306e+09
50%,2386.500000,4259.500000,NaN,NaN,NaN,NaN,75.946297,31.004801,141120.000000,2006.000000,15.000000,5.000000,5.488270e+06,115.00000,4.225000e+02,11.000000,3.090509e+09,3.090509e+09
75%,3684.500000,6320.000000,NaN,NaN,NaN,NaN,76.788902,31.004801,144301.000000,2006.000000,23.000000,6.000000,8.063805e+06,158.00000,6.102500e+02,11.000000,3.170514e+09,3.170514e+09
max,5357.000000,9295.000000,NaN,NaN,NaN,NaN,103.801399,37.750999,800001.000000,2012.000000,31.000000,50.000000,1.485973e+07,995516.00000,2.919881e+06,12.000000,3.180218e+09,3.180218e+09

In [3]:
df.columns

Index(['Response_ID', 'Time_Started', 'Date_Submitted', 'Status', 'Contact_ID',
       'Legacy_Comments', 'Comments', 'Language', 'Referer', 'SessionID',
       'User_Agent', 'Tags', 'IP_Address', 'Longitude', 'Latitude', 'Country',
       'City', 'State/Region', 'Postal', 'New_Hidden_Value', 'name',
       'dob_year', 'dob_month', 'dob_date', 'hh_size', 'mother_education',
       'father_education', 'personal_phone', 'Student_ID',
       'demographic_duration', '1a_grit_localtravel', '1b_grit_localtravel',
       '2a_grit_errands', '2b_grit_errands', '3a_grit_publicspeaking',
       '3b_grit_publicspeaking', '4a_grit_discussion', '4b_grit_discussion',
       '5a_grit_persevered', '5b_grit_persevered', '6a_tnt_extraleadership',
       '6b_tnt_extraleadership', '7a_tnt_newskill', '7b_tnt_newskill',
       '8a_tnt_helpingothers', '8b_tnt_helpingothers', '9a_tnt_risktaking',
       '9b_tnt_risktaking', '10a_tnt_project', '10a_tnt_project_example',
       '10b_tnt_project', '11a_sa_feedback', '11b_sa_feedback',
       '12a_sa_helpseeking', '12b_sa_helpseeking', '13a_sa_values',
       '13b_sa_values', '14a_sa_emotions', '14b_sa_emotions',
       '15a_sa_influence', '15b_sa_influence', '16a_ind_doingthingsalone',
       '16b_sa_doingthingsalone', '17a_ind_againstnorm', '17b_ind_againstnorm',
       '18a_ind_reflection', '18b_ind_reflection', '19a_ind_questioning',
       '19b_ind_questioning', '20a_ind_informeddecision',
       '20b_ind_informeddecision', 'survey_duration', 'open_comment'],
      dtype='object')